# Generated by Django 5.0.2 on 2024-06-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arcticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcticle',
            name='author',
        ),
    ]
