# Generated by Django 4.2.5 on 2024-07-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_referralcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
